SELECT DISTINCT ?entity
WHERE {
   {
      SELECT (?s AS ?entity) WHERE { 
         ?s ?p ?o .
         FILTER(STRSTARTS(STR(?s),"http://purl.obolibrary.org/obo/CL_"))
      }
   }
   UNION
   {
      SELECT (?o AS ?entity) WHERE {
         ?s ?p ?o .
         FILTER(STRSTARTS(STR(?o),"http://purl.obolibrary.org/obo/CL_"))
      }
   }
}