SELECT DISTINCT ?entity
WHERE {
   {
      SELECT (?s AS ?entity) WHERE { 
         ?s ?p ?o .
         FILTER(STRSTARTS(STR(?s),"http://purl.obolibrary.org/obo/UBERON_"))
      }
   }
   UNION
   {
      SELECT (?o AS ?entity) WHERE {
         ?s ?p ?o .
         FILTER(STRSTARTS(STR(?o),"http://purl.obolibrary.org/obo/UBERON_"))
      }
   }
   UNION
   {
      SELECT ?entity WHERE {
         BIND("http://purl.obolibrary.org/obo/UBERON_0001062" AS ?entity)
      }
   }
}