PREFIX ccf: <http://purl.org/ccf/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT DISTINCT ?entity
WHERE {
   ?entity oboInOwl:id ?entity_id .
   FILTER contains(?entity_id, "LMHA:") 
}