SELECT DISTINCT ?entity
WHERE {
   {
      SELECT (?s AS ?entity) WHERE { 
         ?s ?p ?o .
         FILTER(STRSTARTS(STR(?s),"http://identifiers.org/hgnc/"))
      }
   }
   UNION
   {
      SELECT (?o AS ?entity) WHERE {
         ?s ?p ?o .
         FILTER(STRSTARTS(STR(?o),"http://identifiers.org/hgnc/"))
      }
   }
   UNION
   {
      SELECT ?entity WHERE {
         BIND("http://purl.bioontology.org/ontology/HGNC/gene" AS ?entity)
      }
   }
}